const knex = require('knex');

module.exports = {
  async seed(knex) {
    try {
      await knex('destinos').del();

      await knex('destinos').insert([
        {descricao: 'Entre todos os planetas terrestres Mercúrio é um extremo: ele é o menor de todos, o mais denso entre eles (após corrigirmos a auto-compressão), aquele com a mais velha superfície, aquele com a maior de todas as variações diárias na temperatura da superfície, e o menos explorado entre eles.',
         nota: 0.0, numNotas: 0, periculosidade: 7.6, distanciaTerra: 0.39, temETs: false, image1: 'mercurio1.png', image2: 'mercurio2.png', image3: 'mercurio3.png', image4: 'mercurio4.png', nome: 'Mercúrio', tipo: 1 },
        {descricao: 'Vênus é o segundo planeta a partir do Sol e o quarto menor planeta do Sistema Solar. Somente Mercúrio, Marte, e o anão Plutão são menores do que Vênus. De todos os planetas do Sistema Solar Vênus é o que mais se aproxima da Terra. Durante o seu movimento em torno do Sol, Vênus se aproxima a cerca de 40 milhões de quilômetros do nosso planeta. Vênus sempre chamou a atenção dos povos antigos devido à sua intensa presença no céu. Visto da Terra, Vênus pode superar em brilho todos os corpos celestes com excessão do Sol e da Lua. Deste modo Vênus situa-se como o terceiro objeto mais brilhante no céu. Sua luz fraca é suficiente para, em certas ocasiões, criar sombras de objetos no chão durante a noite. Vênus, quando está no máximo de seu brilho, pode ser visto no céu diurno.',
         nota: 0.0, numNotas: 0, periculosidade: 8.7, distanciaTerra: 0.28, temETs: true, image1: 'venus1.jpg', nome: 'Vênus', tipo: 1},
        {descricao: 'Antares é uma estrela supergigante vermelha que está chegando ao fim de sua vida. Quando não houver mais combustível para queimar, a estrela entrará em colapso e explodirá em uma supernova - "quando seu brilho rivalizar com o resto da galáxia", observaram os astrofísicos Paul Butterworth e Mike Arida. A estrela está entre as 20 mais brilhantes visíveis no céu noturno da Terra, embora seu brilho varie. Observadores amadores estimaram sua magnitude aparente entre 0,88 e 1,16. Os nomes em árabe e latino da estrela Antares significam "coração do Escorpião". Se você ver esta constelação no céu, descobrirá que Antares realmente parece residir no coração do Escorpião.',
         nota: 0.0, numNotas: 0, periculosidade: 9.7, distanciaTerra: 600.0, temETs: true, image1: 'antares1.jpg', image2: 'antares2.jpg', nome: 'Antares', tipo: 2},
        {descricao: 'Arcturus é uma estrela gigante vermelha no céu do Hemisfério Norte da Terra e a estrela mais brilhante da constelação de Boötes (o pastor). Arcturus também está entre as estrelas mais brilhantes que podem ser vistas da Terra. Os astrônomos dizem que Arcturus terminará como uma anã branca no final de sua vida. A maneira mais fácil de detectar Arcturus é seguindo a curva do "punho" da Ursa Maior. Hoje, os astrônomos sabem que Arcturus tem muito impacto, apesar de ser apenas cerca de 1,5 vezes a massa do sol. A olho nu, Arcturus parece brilhar cerca de 113 vezes mais que o sol, de acordo com Jim Kaler, professor emérito da Universidade de Illinois em Urbana-Champaign. Arcturus, no entanto, tem uma temperatura mais baixa que o sol, o que significa que grande parte da energia da estrela gigante vermelha é irradiada como calor.',
         nota: 0.0, numNotas: 0, periculosidade: 9.6, distanciaTerra: 36.6, temETs: true, image1: 'arcturus1.jpg', nome: 'Arcturus', tipo: 2},
        {descricao: 'O Cruzeiro do Sul é uma constelação proeminente no céu do sul. É a menor de todas as 88 constelações. Apesar de seu tamanho, é uma das constelações mais conhecidas no hemisfério sul. É facilmente reconhecível pelo asterismo em forma de cruz, formado por suas cinco estrelas mais brilhantes. A constelação está associada a várias histórias e figura com destaque em diferentes mitologias no hemisfério sul. Ele tem uma importância especial na Austrália e na Nova Zelândia, onde é circumpolar e pode ser visto ao longo do ano. O cruzeiro do sul é uma constelação famosa em muitas culturas. Os gregos antigos consideravam que fazia parte da constelação de Centaurus. Os gregos puderam vê-lo antes que suas estrelas caíssem abaixo do horizonte para a Europa e a maior parte do hemisfério norte. Alguns viram significado nisso, ligando o desaparecimento da cruz celestial do céu à crucificação de Cristo. O astrônomo grego do século 2 Ptolomeu listou as estrelas do cruzeiro do sul como parte da constelação Centaurus em seu Almagest. No ano 400 dC, a constelação não era mais visível na maior parte da Europa e os europeus não a redescobriram até as grandes expedições navais do final do século XV e início do século XVI.',
         nota: 0.0, numNotas: 0, periculosidade: 8.5, distanciaTerra: 88.0, temETs: true, image1: 'cruzeiro-do-sul1.jpg', image2: 'cruzeiro-do-sul2.jpg', image3: 'cruzeiro-do-sul1.jpg', nome: 'Cruzeiro do Sul', tipo: 3},
        {descricao: 'A galáxia de Andrômeda, o vizinho mais próximo da Via Láctea, é o objeto mais distante no céu que você pode ver a olho nu - mas apenas em uma noite clara de um local com um céu muito escuro. A galáxia é uma espiral bonita, mas um fato que você pode não estar ciente: estamos seguros por alguns bilhões de anos, mas Andrômeda está seguindo nosso caminho e em rota de colisão com a Via Láctea. A galáxia de Andrômeda e nossa Via Láctea reinam como as duas galáxias mais massivas e dominantes do Grupo Local de Galáxias. A Galáxia de Andrômeda é a maior galáxia do Grupo Local, que, além da Via Láctea, também contém a Galáxia Triangulum e cerca de 30 outras galáxias menores.',
         nota: 0.0, numNotas: 0, periculosidade: 9.1, distanciaTerra: 2537000.0, temETs: true, image1: 'andromeda1.jpg', nome: 'Andrômeda', tipo: 4},
        {descricao: 'O planeta vermelho Marte, nomeado para o deus romano da guerra, há muito tempo é um presságio no céu noturno. E, à sua maneira, a superfície vermelha e enferrujada do planeta conta uma história de destruição. Bilhões de anos atrás, o quarto planeta do Sol poderia ter sido confundido com o gêmeo menor da Terra, com água líquida em sua superfície - e talvez até a vida. Com um raio de 2.106 milhas, Marte é o sétimo maior planeta do nosso sistema solar e cerca de metade do diâmetro da Terra. A gravidade da superfície é de 37,5% da da Terra. Como a Terra e Vênus, Marte tem montanhas, vales e vulcões, mas o planeta vermelho é de longe o maior e mais dramático. O Monte Olimpo, o maior vulcão do sistema solar, se ergue cerca de 26 quilômetros acima da superfície de Marte, tornando-o três vezes mais alto que o Everest. Mas a base do Monte Olimpo é tão larga - a cerca de 60 km de diâmetro - que a inclinação média do vulcão é apenas um pouco mais íngreme do que uma rampa para cadeira de rodas. O pico é tão grande que se curva com a superfície de Marte. Se você estivesse na borda externa do Monte Olimpo, seu cume estaria além do horizonte.',
         nota: 0.0, numNotas: 0, periculosidade: 8.1, distanciaTerra: 0.52, temETs: true, image1: 'marte1.jpg', nome: 'Marte', tipo: 1},
        {descricao: 'Vega é uma estrela brilhante localizada a apenas 25 anos-luz da Terra, visível no céu de verão do Hemisfério Norte. A estrela faz parte da constelação Lyra e, com as estrelas Deneb e Altair, forma um asterismo conhecido como Triângulo do Verão. A estrela tem apenas cerca de 450 milhões de anos, o que a torna jovem em comparação com o nosso próprio sistema solar (com 4,6 bilhões de anos). Os estudos da Vega ajudam os astrônomos a aprender mais sobre os sistemas solares que estão nos estágios iniciais de sua formação. Como o eixo da Terra oscila, nossa percepção do norte muda gradualmente para diferentes estrelas ao longo de um ciclo de 26.000 anos. Vega era a Estrela do Norte há vários milhares de anos e recuperará esse status em cerca de 12.000 anos.',
         nota: 0.0, numNotas: 0, periculosidade: 9.5, distanciaTerra: 25.0, temETs: true, image1: 'vega1.jpg', nome: 'Vega', tipo: 2},
        {descricao: 'Júpiter é o quinto planeta a contar do Sol e de longe o maior. Tem mais do dobro da massa de todos os outros planetas juntos (318 vezes a massa da Terra). Júpiter (também conhecido como Jove; o deus Grego era Zeus) era o Rei dos Deuses, o governante do Olimpo e o protector do estado Romano. Zeus era o filho de Cronus (Saturno). Júpiter é o 4.º objecto mais brilhante do céu (depois do Sol, da Lua e de Vénus; por vezes Marte é mais brilhante). É conhecido desde tempos pré-históricos, mas como uma "estrela errante". Mas em 1610, quando Galileu aponta pela primeira vez um telescópio ao céu, observa as 4 grandes luas de Júpiter: Io, Europa, Ganimedes e Calisto (agora conhecidas como as luas Galileanas) e regista os seus movimentos para a frente e para trás do planeta. Os planetas gasosos não têm superfícies sólidas, o seu material gasoso simplesmente fica mais denso de acordo com a profundidade (o raio e os diâmetros dos planetas são para os níveis correspondentes a uma pressão de 1 atmosfera). O que vemos quando olhamos para estes planetas é o topo das nuvens nas suas atmosferas (um pouco acima do nível de uma atmosfera).',
         nota: 0.0, numNotas: 0, periculosidade: 9.3, distanciaTerra: 4.2, temETs: true, image1: 'jupiter1.jpg', image2: 'jupiter2.jpg', nome: 'Júpiter', tipo: 1},
        {descricao: 'Spica, Alpha Virginis, é a estrela mais brilhante da constelação do sul de Virgem e a 16a estrela mais brilhante do céu. É uma estrela azul subgigante localizada a uma distância de 262 anos-luz da Terra. Spica é realmente um sistema estelar binário próximo. É uma das estrelas binárias maciças mais próximas do sistema solar. O nome Spica (pronunciado / ˈspaɪkə /) vem da frase em latim spīca virginis, que significa "espiga de grão de Virgem". A palavra latina spicum refere-se à espiga de trigo que Virgem segura em sua mão esquerda. Na mitologia grega e romana, a constelação e a estrela estavam associadas a Deméter (Ceres), a deusa da colheita. Spica é brilhante, devido ao seu tamanho e sua relativa proximidade com a Terra. Os componentes do sistema têm um raio de 7,40 e 3,64 vezes o do Sol. Ambas as estrelas são significativamente mais brilhantes que o Sol, com luminosidade total (incluindo radiação ultravioleta) de 12.100 e 1.500 vezes a energia solar. A Spica A e a Spica B pertencem à classe espectral B, que as torna em branco azulado. As estrelas também são muito mais quentes que o Sol, com temperaturas estimadas da superfície de 22.400 K e 18.500 K, em comparação com os 5.800 K. do Sol. Isso faz de Spica uma das estrelas mais quentes de primeira magnitude.',
         nota: 0.0, numNotas: 0, periculosidade: 9.5, distanciaTerra: 262.0, temETs: true, image1: 'spica1.jpg', nome: 'Spica', tipo: 2},
        {descricao: 'Este colosso é o buraco negro supermassivo que fica no centro da Via Láctea, perto da fronteira das constelações de Sagitário e Escorpião. Seu nome pronuncia-se “Sagitário A Estrela” e faz parte de um objeto ainda maior, chamado "Sagittarius A". Está localizado a 25.640 anos-luz de distância e possui mais de 4 milhões de massas solares.',
         nota: 0.0, numNotas: 0, periculosidade: 9.9, distanciaTerra: 25640.0, temETs: false, image1: 'sagittariusa1.jpg', nome: 'Sagittarius A', tipo: 5},
        ]);
    } catch(err) {
      console.error(err);
    }
  }
}